# Generated by Django 4.2.1 on 2023-05-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0005_lead_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leads.userprofile"
            ),
        ),
    ]
